### PR TITLE
[vf-CI.yml GH Action] add ttfa install step

### PR DESCRIPTION
**Pull request by chrissimpkins**
Adds ttfautohint installation to GH Action configuration to address missing ttfautohint at fontmake `-a` flag autohint step of the build process.

### CODE REVIEW

**Comment by chrissimpkins** [comment]
@vv-monsalve Works! :)

**Comment by vv-monsalve** [comment]
Thanks, @chrissimpkins 

After the merge and before any rebase or PR to include that change in the QA-SpaceGrotesk branch, I took that difference as an opportunity to test two different approaches to set up the Actions.

**On Master branch:** The new .yml file that includes de Ubuntu package manager for ttfautohint, with the requeriments.txt file in that branch.
Result: It worked 

**On QA branch:** Uses the previous .yml file, but I added the python wrapper to the [requirements file](https://github.com/vv-monsalve/space-grotesk/blob/QA-SpaceGrotesk/requirements.txt). 
Result: ttfautohint was [supposedly installed](https://github.com/vv-monsalve/space-grotesk/runs/972282272?check_suite_focus=true#step:5:44), but the build threw the same error "Could not launch ttfautohint."

Could the QA-Branch approach work at all? What would be missing for it to work?

**Comment by chrissimpkins** [comment]
Not through the fontmake autohinter.  If you want to use ttfautohint-py, remove the -a flag from all fontmake builds and use ttfautohint-py to hint the files after the compiles are complete (ie., after your build script step and before your fontbakery step).

**Comment by vv-monsalve** [comment]
Ok! I got it now. Thanks!

**Pull request merged**
